# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=45)),
                ('lastname', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=45)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
