# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 02:33
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=45, verbose_name=django.contrib.auth.models.User)),
                ('lastname', models.CharField(default='', max_length=60, verbose_name=django.contrib.auth.models.User)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=45, verbose_name=django.contrib.auth.models.User)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
