# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images')),
                ('details', models.CharField(max_length=255)),
                ('history', models.TextField()),
                ('quantity', models.IntegerField()),
                ('artefact', models.CharField(choices=[('HIS', 'History'), ('CUL', 'Culture'), ('REL', 'Religion'), ('MED', 'Media')], max_length=2)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
